# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_style', '0007_style_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='class_name',
            field=models.CharField(blank=True, choices=[('intro-features', 'intro-features'), ('card-media-aside', 'card-media-aside'), ('centered-content', 'centered-content'), ('summaries', 'summaries'), ('footer-hero', 'footer-hero')], max_length=255, verbose_name='Class name'),
        ),
    ]
